<?php
use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;
use yii\helpers\Url;

 $this->title = 'FiscalBridge Portal Login';
 $this->context->layout = false;

 // Get security stamp from session (generated by controller)
 $securityAnswer = Yii::$app->session->get('security_stamp_answer');
 $securityQuestion = Yii::$app->session->get('security_stamp_question');
 
 // If not set, generate one (fallback)
 if (!$securityAnswer || !$securityQuestion) {
     $number1 = rand(5, 15);
     $number2 = rand(8, 25);
     $correctAnswer = $number1 + $number2;
     $question = "$number1 + $number2";
     Yii::$app->session->set('security_stamp_answer', $correctAnswer);
     Yii::$app->session->set('security_stamp_question', $question);
 } else {
     // Parse question to extract numbers for display
     preg_match('/(\d+)\s*\+\s*(\d+)/', $securityQuestion, $matches);
     $number1 = isset($matches[1]) ? (int)$matches[1] : rand(5, 15);
     $number2 = isset($matches[2]) ? (int)$matches[2] : rand(8, 25);
     $correctAnswer = $securityAnswer;
 }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #006a71;
            --secondary: #f39c12;
            --accent: #3498db;
            --dark: #2c3e50;
            --light: #ecf0f1;
            --success: #27ae60;
            --danger: #e74c3c;
            --warning: #f39c12;
            --info: #3498db;
            --gradient-primary: linear-gradient(135deg, #006a71, #00a0a9);
            --gradient-secondary: linear-gradient(135deg, #f39c12, #f1c40f);
            --gradient-accent: linear-gradient(135deg, #3498db, #2980b9);
            --shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            --shadow-hover: 0 15px 35px rgba(0, 0, 0, 0.15);
            --transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background: linear-gradient(135deg, #f5f7fa, #c3cfe2);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            color: var(--dark);
            overflow-x: hidden;
        }

        /* Animated Background */
        .bg-animation {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            overflow: hidden;
        }

        .bg-animation span {
            position: absolute;
            display: block;
            list-style: none;
            width: 20px;
            height: 20px;
            background: rgba(0, 106, 113, 0.1);
            animation: move 25s linear infinite;
            bottom: -150px;
        }

        .bg-animation span:nth-child(1) {
            left: 25%;
            width: 80px;
            height: 80px;
            animation-delay: 0s;
        }

        .bg-animation span:nth-child(2) {
            left: 10%;
            width: 20px;
            height: 20px;
            animation-delay: 2s;
            animation-duration: 12s;
        }

        .bg-animation span:nth-child(3) {
            left: 70%;
            width: 20px;
            height: 20px;
            animation-delay: 4s;
        }

        .bg-animation span:nth-child(4) {
            left: 40%;
            width: 60px;
            height: 60px;
            animation-delay: 0s;
            animation-duration: 18s;
        }

        .bg-animation span:nth-child(5) {
            left: 65%;
            width: 20px;
            height: 20px;
            animation-delay: 0s;
        }

        .bg-animation span:nth-child(6) {
            left: 75%;
            width: 110px;
            height: 110px;
            animation-delay: 3s;
        }

        .bg-animation span:nth-child(7) {
            left: 35%;
            width: 150px;
            height: 150px;
            animation-delay: 7s;
        }

        .bg-animation span:nth-child(8) {
            left: 50%;
            width: 25px;
            height: 25px;
            animation-delay: 15s;
            animation-duration: 45s;
        }

        .bg-animation span:nth-child(9) {
            left: 20%;
            width: 15px;
            height: 15px;
            animation-delay: 2s;
            animation-duration: 35s;
        }

        .bg-animation span:nth-child(10) {
            left: 85%;
            width: 150px;
            height: 150px;
            animation-delay: 0s;
            animation-duration: 11s;
        }

        @keyframes move {
            0% {
                transform: translateY(0) rotate(0deg);
                opacity: 1;
                border-radius: 0;
            }
            100% {
                transform: translateY(-1000px) rotate(720deg);
                opacity: 0;
                border-radius: 50%;
            }
        }

        .login-container {
            width: 100%;
            max-width: 1000px;
            background: rgba(255, 255, 255, 0.95);
            border-radius: 20px;
            box-shadow: var(--shadow-hover);
            overflow: hidden;
            display: flex;
            backdrop-filter: blur(10px);
            animation: slideUp 0.8s cubic-bezier(0.34, 1.56, 0.64, 1);
            position: relative;
            z-index: 10;
        }

        @keyframes slideUp {
            from {
                opacity: 0;
                transform: translateY(50px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .login-left {
            flex: 1;
            background: var(--gradient-primary);
            padding: 60px 40px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: white;
            position: relative;
            overflow: hidden;
        }

        .login-left::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><rect width="100" height="100" fill="none" stroke="rgba(255,255,255,0.1)" stroke-width="1"/></svg>');
            background-size: 20px 20px;
            opacity: 0.3;
        }

        .login-left h2 {
            font-size: 2.5rem;
            font-weight: 700;
            margin-bottom: 20px;
            text-align: center;
            position: relative;
            z-index: 1;
        }

        .login-left .portal-description {
            font-size: 1.1rem;
            text-align: center;
            max-width: 320px;
            margin-bottom: 30px;
            position: relative;
            z-index: 1;
            line-height: 1.6;
        }

        .login-left .organizations {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-bottom: 30px;
            position: relative;
            z-index: 1;
            width: 100%;
        }

        .login-left .organization {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
            background: rgba(255, 255, 255, 0.1);
            padding: 15px;
            border-radius: 15px;
            backdrop-filter: blur(5px);
            transition: var(--transition);
            width: 100%;
            max-width: 320px;
        }

        .login-left .organization:hover {
            background: rgba(255, 255, 255, 0.2);
            transform: translateY(-3px);
        }

        .login-left .organization img {
            width: 60px;
            height: 60px;
            margin-right: 15px;
            border-radius: 8px;
            object-fit: contain;
        }

        .login-left .organization-info {
            flex: 1;
        }

        .login-left .organization-name {
            font-weight: 600;
            font-size: 1rem;
            margin-bottom: 5px;
        }

        .login-left .organization-role {
            font-size: 0.85rem;
            opacity: 0.9;
        }

        .login-features {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-top: 20px;
            position: relative;
            z-index: 1;
        }

        .feature-badge {
            display: inline-flex;
            align-items: center;
            background: rgba(0, 106, 113, 0.1);
            color: var(--primary);
            padding: 5px 12px;
            border-radius: 20px;
            font-size: 0.75rem;
            margin: 5px;
            font-weight: 500;
        }

        .feature-badge i {
            margin-right: 5px;
        }

        .login-right {
            flex: 1.5;
            padding: 50px;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

        .login-header {
            margin-bottom: 30px;
            text-align: center;
        }

        .login-title {
            font-size: 2.5rem;
            font-weight: 700;
            margin-bottom: 10px;
            background: var(--gradient-primary);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            position: relative;
            display: inline-block;
        }

        .login-title::after {
            content: '';
            position: absolute;
            bottom: -5px;
            left: 10%;
            width: 80%;
            height: 4px;
            background: var(--gradient-secondary);
            border-radius: 2px;
        }

        .login-subtitle {
            color: #7f8c8d;
            font-size: 1.1rem;
        }

        .date-today {
            position: absolute;
            top: 20px;
            right: 20px;
            background: rgba(255, 255, 255, 0.8);
            padding: 8px 15px;
            border-radius: 30px;
            font-size: 0.9rem;
            color: var(--dark);
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(5px);
        }

        .form-group {
            margin-bottom: 25px;
            position: relative;
        }

        .form-label {
            font-weight: 600;
            color: var(--dark);
            margin-bottom: 10px;
            display: block;
            font-size: 0.95rem;
        }

        .form-control {
            width: 100%;
            padding: 15px 15px 15px 45px;
            font-size: 1rem;
            border: 2px solid #e0e0e0;
            border-radius: 10px;
            background: #f8f9fa;
            transition: var(--transition);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);
        }

        .form-control:focus {
            border-color: var(--primary);
            background: white;
            box-shadow: 0 0 0 4px rgba(0, 106, 113, 0.1);
            outline: none;
        }

        .password-wrapper {
            position: relative;
        }

        .toggle-password {
            position: absolute;
            left: 15px;
            top: 50%;
            transform: translateY(-50%);
            cursor: pointer;
            color: #95a5a6;
            font-size: 1.2rem;
            transition: var(--transition);
            z-index: 2;
        }

        .toggle-password:hover {
            color: var(--primary);
        }

        .caps-lock-warning {
            font-size: 0.85rem;
            color: var(--danger);
            margin-top: 8px;
            display: none;
            animation: pulse 1.5s infinite;
        }

        @keyframes pulse {
            0%, 100% { opacity: 0.6; }
            50% { opacity: 1; }
        }

        .strength-meter {
            height: 6px;
            background-color: #e0e0e0;
            border-radius: 3px;
            margin-top: 10px;
            overflow: hidden;
            display: none;
        }

        .strength-meter-fill {
            height: 100%;
            width: 0;
            border-radius: 3px;
            transition: width 0.5s ease, background-color 0.5s ease;
        }

        .strength-labels {
            display: flex;
            justify-content: space-between;
            margin-top: 5px;
            font-size: 0.75rem;
            color: #7f8c8d;
            display: none;
        }

        .password-strength-text {
            font-size: 0.75rem;
            margin-top: 5px;
            text-align: right;
            font-weight: 500;
            display: none;
        }

        .password-strength-weak { color: var(--danger); }
        .password-strength-medium { color: var(--warning); }
        .password-strength-strong { color: var(--success); }

        .security-stamp-wrapper {
            display: flex;
            align-items: center;
            gap: 15px;
            margin-top: 10px;
            padding: 15px;
            background: rgba(0, 106, 113, 0.05);
            border-radius: 10px;
            border: 2px dashed var(--primary);
        }

        #security-question {
            font-size: 1.2rem;
            font-weight: 600;
            color: var(--primary);
            min-width: 120px;
            text-align: center;
        }

        .refresh-security-stamp {
            background: none;
            border: none;
            font-size: 1.5rem;
            color: var(--primary);
            cursor: pointer;
            transition: var(--transition);
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .refresh-security-stamp:hover {
            background: rgba(0, 106, 113, 0.1);
            transform: rotate(180deg);
        }

        .options-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin: 20px 0;
            flex-wrap: wrap;
            gap: 10px;
            font-size: 0.9rem;
        }

        /* Fix Yii checkbox rendering */
        .options-container .form-check {
            display: flex;
            align-items: center;
            margin: 0;
            padding: 0;
        }

        .options-container .form-check-input {
            margin-right: 6px; /* spacing between box and label */
        }

        .options-container .form-check-label {
            margin: 0;
            white-space: nowrap; /* prevent breaking into 2 lines */
            font-weight: 500;
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .options-container a {
            display: flex;
            align-items: center;
            gap: 5px;
            font-size: 0.9rem;
            white-space: nowrap; /* keep link on one line */
            color: var(--primary);
            text-decoration: none;
            font-weight: 500;
            transition: var(--transition);
        }

        .options-container a:hover {
            color: var(--accent);
            text-decoration: underline;
        }

        .form-check {
            display: flex;
            align-items: center;
        }

        .form-check-input {
            width: 20px;
            height: 20px;
            margin-right: 10px;
            cursor: pointer;
        }

        .form-check-label {
            cursor: pointer;
            user-select: none;
            font-weight: 500;
        }

        .btn {
            padding: 15px;
            font-size: 1rem;
            font-weight: 600;
            border-radius: 10px;
            border: none;
            cursor: pointer;
            transition: var(--transition);
            text-transform: uppercase;
            letter-spacing: 1px;
            position: relative;
            overflow: hidden;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        }

        .btn-primary {
            background: var(--gradient-primary);
            color: white;
            width: 100%;
            margin-top: 10px;
        }

        .btn-primary:hover {
            transform: translateY(-3px);
            box-shadow: 0 7px 20px rgba(0, 106, 113, 0.3);
        }

        .btn-primary::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
            transition: left 0.5s;
        }

        .btn-primary:hover::before {
            left: 100%;
        }

        .btn-secondary {
            background: var(--gradient-accent);
            color: white;
            width: 100%;
            margin-top: 10px;
        }

        .btn-secondary:hover {
            transform: translateY(-3px);
            box-shadow: 0 7px 20px rgba(52, 152, 219, 0.3);
        }

        .invalid-feedback {
            display: block;
            color: var(--danger);
            font-size: 0.85rem;
            margin-top: 8px;
            animation: shake 0.5s;
        }

        @keyframes shake {
            0%, 100% { transform: translateX(0); }
            10%, 30%, 50%, 70%, 90% { transform: translateX(-5px); }
            20%, 40%, 60%, 80% { transform: translateX(5px); }
        }

        .btn-loading {
            color: transparent;
            pointer-events: none;
        }

        .btn-loading::after {
            content: "";
            position: absolute;
            width: 20px;
            height: 20px;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            margin: auto;
            border: 2px solid transparent;
            border-top-color: #fff;
            border-radius: 50%;
            animation: spinner 0.8s linear infinite;
        }

        @keyframes spinner {
            to { transform: rotate(360deg); }
        }

        .toast-container {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1050;
        }

        .toast {
            background: white;
            border-radius: 10px;
            box-shadow: var(--shadow);
            overflow: hidden;
            margin-bottom: 10px;
            animation: slideInRight 0.3s ease-out;
            max-width: 350px;
        }

        @keyframes slideInRight {
            from { transform: translateX(100%); }
            to { transform: translateX(0); }
        }

        .toast-header {
            display: flex;
            align-items: center;
            padding: 12px 15px;
            border-bottom: 1px solid #eee;
        }

        .toast-title {
            font-weight: 600;
            margin: 0 auto;
        }

        .toast-close {
            background: none;
            border: none;
            font-size: 1.2rem;
            cursor: pointer;
            color: #999;
        }

        .toast-body {
            padding: 15px;
        }

        .toast-success { border-left: 4px solid var(--success); }
        .toast-error { border-left: 4px solid var(--danger); }
        .toast-info { border-left: 4px solid var(--info); }

        .keyboard-hint {
            position: absolute;
            bottom: 10px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 0.75rem;
            color: #999;
            opacity: 0;
            transition: opacity 0.3s;
        }

        .login-container:hover .keyboard-hint {
            opacity: 1;
        }

        .input-group-icon {
            position: relative;
        }

        .input-group-icon i {
            position: absolute;
            left: 15px;
            top: 50%;
            transform: translateY(-50%);
            color: #95a5a6;
            font-size: 1.1rem;
        }

        .input-group-icon .form-control {
            padding-left: 45px;
        }

        @media (max-width: 992px) {
            .login-container {
                flex-direction: column;
                max-width: 500px;
            }
            
            .login-left {
                padding: 40px 30px;
                min-height: 250px;
            }
            
            .login-left h2 {
                font-size: 2rem;
            }
            
            .login-right {
                padding: 40px 30px;
            }
            
            .login-title {
                font-size: 2rem;
            }
            
            .date-today {
                position: static;
                margin-bottom: 20px;
                align-self: flex-end;
            }
        }

        @media (max-width: 576px) {
            body {
                padding: 10px;
            }
            
            .login-container {
                border-radius: 15px;
            }
            
            .login-left {
                padding: 30px 20px;
            }
            
            .login-left h2 {
                font-size: 1.8rem;
            }
            
            .login-right {
                padding: 30px 20px;
            }
            
            .login-title {
                font-size: 1.8rem;
            }
            
            .security-stamp-wrapper {
                flex-direction: column;
                align-items: flex-start;
            }
            
            #security-question {
                margin-bottom: 10px;
                min-width: auto;
            }
            
            .options-container {
                flex-direction: column;
                align-items: flex-start;
                gap: 15px;
            }
        }

        @media (max-width: 400px) {
            .login-left .organization {
                flex-direction: column;
                text-align: center;
            }
            
            .login-left .organization img {
                margin-right: 0;
                margin-bottom: 10px;
            }
            
            .login-title {
                font-size: 1.6rem;
            }
            
            .form-control {
                padding: 12px 12px 12px 40px;
                font-size: 0.9rem;
            }
            
            .input-group-icon .form-control {
                padding-left: 40px;
            }
            
            .btn {
                padding: 12px;
                font-size: 0.9rem;
            }
        }
    </style>
</head>
<body>
    <!-- Animated Background -->
    <div class="bg-animation">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
    
    <div class="login-container">
        <div class="login-left">
            <h2>FiscalBridge</h2>
            <p class="portal-description">Secure Portal for The National Treasury & Economic Planning</p>
            
            <div class="organizations">
                <div class="organization">
                    <img src="<?= Url::to('@web/igfr_front/img/nt.png') ?>" alt="National Treasury Logo">
                    <div class="organization-info">
                        <div class="organization-name">The National Treasury</div>
                        <div class="organization-role">Economic Planning</div>
                    </div>
                </div>
                
                <div class="organization">
                    <img src="<?= Url::to('@web/igfr_front/img/eq.png') ?>" alt="Equalization Fund Logo">
                    <div class="organization-info">
                        <div class="organization-name">Equalization Fund</div>
                        <div class="organization-role">Regional Development</div>
                    </div>
                </div>
            </div>
            
            <div class="login-features">
                <span class="feature-badge"><i class="bi bi-shield-check"></i> Secure</span>
                <span class="feature-badge"><i class="bi bi-lightning-charge"></i> Fast</span>
                <span class="feature-badge"><i class="bi bi-phone"></i> Responsive</span>
            </div>
        </div>

        <div class="login-right">
            <div class="date-today" id="current-date"></div>

            <div class="login-header">
                <h1 class="login-title">System Login</h1>
                <p class="login-subtitle">Please fill out the fields below to login:</p>
            </div>

            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'action' => ['/ef/default/login'],
                'method' => 'post',
                'fieldConfig' => [
                    'template' => "{label}\n{input}\n{error}",
                    'labelOptions' => ['class' => 'form-label'],
                    'inputOptions' => ['class' => 'form-control'],
                    'errorOptions' => ['class' => 'invalid-feedback'],
                ],
            ]); ?>

            <div class="input-group-icon">
                <i class="bi bi-person"></i>
                <?= $form->field($model, 'username')->textInput([
                    'autofocus' => true,
                    'placeholder' => 'Enter your username or email'
                ])->label(false) ?>
            </div>

            <div class="password-wrapper">
                <i class="bi bi-eye-slash toggle-password" id="toggle-password"></i>
                <?= $form->field($model, 'password')->passwordInput([
                    'id' => 'password-input',
                    'placeholder' => 'Enter your password'
                ])->label(false) ?>
            </div>

            <div id="caps-lock-warning" class="caps-lock-warning">
                <small><i class="bi bi-exclamation-triangle"></i> Caps Lock is ON</small>
            </div>

            <div class="strength-meter" id="strength-meter">
                <div class="strength-meter-fill" id="strength-meter-fill"></div>
            </div>
            <div class="strength-labels">
                <span>Weak</span>
                <span>Medium</span>
                <span>Strong</span>
            </div>
            <div class="password-strength-text" id="password-strength-text"></div>

            <div class="form-group">
                <label class="form-label"><i class="bi bi-shield-check"></i> Security Stamp</label>
                <div class="security-stamp-wrapper">
                    <span id="security-question"><?= $securityQuestion ?? "$number1 + $number2" ?> =</span>
                    <button type="button" class="refresh-security-stamp" id="refresh-security-stamp" title="Refresh Security Stamp">
                        <i class="bi bi-arrow-repeat"></i>
                    </button>
                    <?= $form->field($model, 'securityStamp')->textInput([
                        'id' => 'security-answer',
                        'placeholder' => 'Answer'
                    ])->label(false) ?>
                    <input type="hidden" id="correct-answer" name ="correct_answer" value="<?= $correctAnswer ?>">
                </div>
            </div>

            <div class="options-container">
                <div class="form-check">
                    <?= $form->field($model, 'rememberMe')->checkbox([
                        'template' => "{input} {label}",
                        'labelOptions' => ['class' => 'form-check-label'],
                        'options' => ['class' => 'form-check-input']
                    ]) ?>
                </div>
                
                <?= Html::a('<i class="bi bi-question-circle"></i> Forgot Password?', 
                    ['/ef/user/reset-password'], 
                    ['class' => 'text-decoration-none fw-medium']) ?>
            </div>

            <?= Html::submitButton('<i class="bi bi-box-arrow-in-right"></i> Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            <?= Html::a('<i class="bi bi-arrow-clockwise"></i> Reset Password', ['/ef/user/reset-password'], ['class' => 'btn btn-secondary']) ?>

            <?php ActiveForm::end(); ?>
            
            <div class="keyboard-hint">
                <i class="bi bi-keyboard"></i> Press Enter to login, Esc to reset
            </div>
        </div>
    </div>

    <div class="toast-container" id="toast-container"></div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        // Display flash messages from server IMMEDIATELY
        <?php if ($error = Yii::$app->session->getFlash('error')): ?>
            console.log('Error flash message:', '<?= addslashes($error) ?>');
            showToast('<?= addslashes($error) ?>', 'error');
        <?php endif; ?>
        <?php if ($success = Yii::$app->session->getFlash('success')): ?>
            console.log('Success flash message:', '<?= addslashes($success) ?>');
            showToast('<?= addslashes($success) ?>', 'success');
        <?php endif; ?>
        <?php if ($info = Yii::$app->session->getFlash('info')): ?>
            console.log('Info flash message:', '<?= addslashes($info) ?>');
            showToast('<?= addslashes($info) ?>', 'info');
        <?php endif; ?>
        
        // Also display Yii validation errors
        <?php if ($model->hasErrors()): ?>
            <?php foreach ($model->getErrors() as $attribute => $errorMessages): ?>
                <?php foreach ($errorMessages as $error): ?>
                    console.log('Validation error:', '<?= addslashes($error) ?>');
                    showToast('<?= addslashes($error) ?>', 'error');
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        
        // Current date
        const dateElement = document.getElementById('current-date');
        if (dateElement) {
            const today = new Date();
            const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
            dateElement.textContent = today.toLocaleDateString(undefined, options);
        }
        
        // Password visibility toggle
        const togglePassword = document.getElementById('toggle-password');
        const passwordInput = document.getElementById('password-input');
        
        if (togglePassword && passwordInput) {
            togglePassword.addEventListener('click', function() {
                if (passwordInput.type === 'password') {
                    passwordInput.type = 'text';
                    this.classList.replace('bi-eye-slash', 'bi-eye');
                } else {
                    passwordInput.type = 'password';
                    this.classList.replace('bi-eye', 'bi-eye-slash');
                }
            });
            
            // Caps lock warning
            const capsLockWarning = document.getElementById('caps-lock-warning');
            passwordInput.addEventListener('keyup', function(e) {
                capsLockWarning.style.display = e.getModifierState('CapsLock') ? 'block' : 'none';
            });
            
            // Password strength meter
            const strengthMeter = document.getElementById('strength-meter');
            const strengthMeterFill = document.getElementById('strength-meter-fill');
            const strengthLabels = document.querySelector('.strength-labels');
            const strengthText = document.getElementById('password-strength-text');
            
            passwordInput.addEventListener('input', function() {
                const val = passwordInput.value;
                
                // Show strength meter only when user starts typing
                if (val.length > 0) {
                    strengthMeter.style.display = 'block';
                    strengthLabels.style.display = 'flex';
                    strengthText.style.display = 'block';
                } else {
                    strengthMeter.style.display = 'none';
                    strengthLabels.style.display = 'none';
                    strengthText.style.display = 'none';
                    return;
                }
                
                let strength = 0;
                let strengthLabel = '';
                
                if (val.length >= 8) strength += 25;
                if (/[A-Z]/.test(val)) strength += 25;
                if (/[0-9]/.test(val)) strength += 25;
                if (/[^A-Za-z0-9]/.test(val)) strength += 25;
                
                strengthMeterFill.style.width = `${strength}%`;
                
                if (strength <= 25) {
                    strengthMeterFill.style.backgroundColor = '#e74c3c';
                    strengthLabel = 'Weak Password';
                    strengthText.className = 'password-strength-text password-strength-weak';
                } else if (strength <= 50) {
                    strengthMeterFill.style.backgroundColor = '#f39c12';
                    strengthLabel = 'Medium Password';
                    strengthText.className = 'password-strength-text password-strength-medium';
                } else if (strength <= 75) {
                    strengthMeterFill.style.backgroundColor = '#3498db';
                    strengthLabel = 'Good Password';
                    strengthText.className = 'password-strength-text password-strength-medium';
                } else {
                    strengthMeterFill.style.backgroundColor = '#27ae60';
                    strengthLabel = 'Strong Password';
                    strengthText.className = 'password-strength-text password-strength-strong';
                }
                
                strengthText.textContent = strengthLabel;
            });
        }
        
        // Toast notification function
        function showToast(message, type = 'info') {
            const toastContainer = document.getElementById('toast-container');
            const toast = document.createElement('div');
            toast.className = `toast toast-${type}`;
            
            let iconClass = '';
            if (type === 'success') iconClass = 'bi-check-circle-fill text-success';
            else if (type === 'error') iconClass = 'bi-exclamation-circle-fill text-danger';
            else iconClass = 'bi-info-circle-fill text-info';
            
            toast.innerHTML = `
                <div class="toast-header">
                    <i class="bi ${iconClass} me-2"></i>
                    <strong class="toast-title">${type.charAt(0).toUpperCase() + type.slice(1)}</strong>
                    <button type="button" class="toast-close">&times;</button>
                </div>
                <div class="toast-body">${message}</div>
            `;
            
            toastContainer.appendChild(toast);
            
            // Auto remove after 5 seconds
            setTimeout(() => {
                toast.style.animation = 'slideInRight .3s ease-out reverse';
                setTimeout(() => toast.remove(), 300);
            }, 5000);
            
            // Close button
            toast.querySelector('.toast-close').addEventListener('click', () => {
                toast.style.animation = 'slideInRight .3s ease-out reverse';
                setTimeout(() => toast.remove(), 300);
            });
        }
        
        // Security stamp validation
        const loginForm = document.getElementById('login-form');
        const loginButton = loginForm.querySelector('button[type="submit"]');
        
        loginForm?.addEventListener('submit', function(e) {
            console.log('Form submitting...');
            const userAnswer = parseInt(document.getElementById('security-answer').value, 10);
            const correctAnswer = parseInt(document.getElementById('correct-answer').value, 10);
            
            console.log('User answer:', userAnswer, 'Correct answer:', correctAnswer);
            
            if (isNaN(userAnswer) || userAnswer !== correctAnswer) {
                e.preventDefault();
                console.log('Security stamp validation failed - preventing submit');
                showToast('Incorrect Security Stamp. Please try again.', 'error');
                
                const securityStampField = document.getElementById('security-answer');
                securityStampField.classList.add('is-invalid');
                securityStampField.focus();
                
                setTimeout(() => {
                    securityStampField.classList.remove('is-invalid');
                }, 1000);
                return false;
            } else {
                console.log('Security stamp valid - allowing submit');
                loginButton.classList.add('btn-loading');
                loginButton.disabled = true;
                showToast('Authenticating...', 'info');
                // Allow form to submit
                return true;
            }
        });
        
        // Refresh security stamp
        const refreshBtn = document.getElementById('refresh-security-stamp');
        refreshBtn?.addEventListener('click', function() {
            const num1 = Math.floor(Math.random() * 10) + 1;
            const num2 = Math.floor(Math.random() * 20) + 1;
            const answer = num1 + num2;
            
            const questionElement = document.getElementById('security-question');
            questionElement.style.opacity = '0';
            
            setTimeout(() => {
                questionElement.textContent = `${num1} + ${num2} =`;
                questionElement.style.opacity = '1';
            }, 300);
            
            document.getElementById('correct-answer').value = answer;
            document.getElementById('security-answer').value = '';
            showToast('Security stamp refreshed', 'success');
        });
        
        // Keyboard shortcuts
        document.addEventListener('keydown', function(e) {
            // Enter to submit
            if (e.key === 'Enter' && document.activeElement.tagName !== 'BUTTON') {
                e.preventDefault();
                loginForm.dispatchEvent(new Event('submit'));
            }
            
            // Escape to reset
            if (e.key === 'Escape') {
                loginForm.reset();
                document.getElementById('security-answer').value = '';
                document.getElementById('strength-meter-fill').style.width = '0';
                document.getElementById('password-strength-text').textContent = '';
                document.getElementById('strength-meter').style.display = 'none';
                document.querySelector('.strength-labels').style.display = 'none';
                document.getElementById('password-strength-text').style.display = 'none';
                showToast('Form reset', 'info');
            }
        });
        
        // Remember username functionality
        const rememberMeCheckbox = document.querySelector('input[name="LoginForm[rememberMe]"]');
        const usernameInput = document.querySelector('input[name="LoginForm[username]"]');
        
        // Load saved username if exists
        const savedUsername = localStorage.getItem('rememberedUsername');
        if (savedUsername && rememberMeCheckbox) {
            usernameInput.value = savedUsername;
            rememberMeCheckbox.checked = true;
        }
        
        // Save username when "Remember me" is checked
        rememberMeCheckbox?.addEventListener('change', function() {
            if (this.checked) {
                localStorage.setItem('rememberedUsername', usernameInput.value);
            } else {
                localStorage.removeItem('rememberedUsername');
            }
        });
        
        // Update saved username when it changes
        usernameInput?.addEventListener('input', function() {
            if (rememberMeCheckbox.checked) {
                localStorage.setItem('rememberedUsername', this.value);
            }
        });
        
        // Form field animations
        const formInputs = document.querySelectorAll('.form-control');
        formInputs.forEach(input => {
            input.addEventListener('focus', function() {
                this.parentElement.classList.add('focused');
            });
            
            input.addEventListener('blur', function() {
                this.parentElement.classList.remove('focused');
            });
        });
        
        // Auto-refresh security stamp every 60 seconds
        setInterval(() => {
            if (document.visibilityState === 'visible') {
                refreshBtn.click();
            }
        }, 60000);
    });
    </script>
</body>
</html>